name: Demo of stackql-deploy using GitHub Actions

on:
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  deploy-aws-stack:
    name: Deploy AWS Stack
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy a Stack
        uses: stackql/stackql-deploy-action@v1
        with:
          command: 'build'
          stack_dir: 'aws-stack'
          stack_env: 'dev'
          env_vars: 'AWS_REGION=us-east-1'
